"use client";

import Link from "next/link";
import { useState } from "react";
import { FormStatus } from "@/components/auth/form-status";
import { SelectField, TextField } from "@/components/auth/field";
import { ApiError, register, type RegisterRequest } from "@/lib/api";
import styles from "@/styles/auth.module.css";

const initial: RegisterRequest = { firstName: "", lastName: "", documentType: "CC", documentNumber: "", email: "", phone: "", password: "" };
const fieldLabels: Record<string, string> = { firstName: "Ingresa tus nombres.", lastName: "Ingresa tus apellidos.", documentType: "Selecciona el tipo de documento.", documentNumber: "Ingresa el número de documento.", email: "Ingresa un correo válido.", phone: "Ingresa el teléfono.", password: "Ingresa una contraseña." };

export function RegistrationForm() {
  const [values, setValues] = useState(initial); const [errors, setErrors] = useState<Record<string, string>>({}); const [status, setStatus] = useState<{ error?: string; success?: string }>({}); const [submitting, setSubmitting] = useState(false);
  const set = (name: keyof RegisterRequest, value: string) => { setValues((previous) => ({ ...previous, [name]: value })); setErrors((previous) => ({ ...previous, [name]: "" })); };
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const nextErrors: Record<string, string> = {}; (Object.keys(values) as (keyof RegisterRequest)[]).forEach((key) => { if (!values[key].trim()) nextErrors[key] = fieldLabels[key]; }); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) nextErrors.email = fieldLabels.email; if (Object.keys(nextErrors).length) { setErrors(nextErrors); setStatus({ error: "Revisa los campos señalados para continuar." }); return; } setSubmitting(true); setStatus({}); try { await register(values); setStatus({ success: "Tu cuenta fue creada. Ya puedes iniciar sesión." }); setValues(initial); } catch (error) { const apiError = error instanceof ApiError ? error : null; const mapped = Object.fromEntries((apiError?.payload.fields || []).map((field) => [field, "Revisa este dato."])); setErrors(mapped); setStatus({ error: apiError?.status === 409 ? "Ya existe una cuenta con ese correo o documento." : apiError?.message || "No fue posible crear la cuenta. Inténtalo de nuevo." }); } finally { setSubmitting(false); } }
  return <form className={styles.authFields} noValidate onSubmit={submit} aria-busy={submitting}><FormStatus {...status} /><div className={styles.authTwoColumns}><TextField id="firstName" label="Nombres" autoComplete="given-name" disabled={submitting} error={errors.firstName} value={values.firstName} onChange={(e) => set("firstName", e.target.value)} /><TextField id="lastName" label="Apellidos" autoComplete="family-name" disabled={submitting} error={errors.lastName} value={values.lastName} onChange={(e) => set("lastName", e.target.value)} /></div><div className={styles.authTwoColumns}><SelectField id="documentType" label="Tipo de documento" disabled={submitting} error={errors.documentType} value={values.documentType} onChange={(e) => set("documentType", e.target.value)}><option value="CC">Cédula de ciudadanía</option><option value="CE">Cédula de extranjería</option><option value="TI">Tarjeta de identidad</option></SelectField><TextField id="documentNumber" label="Número de documento" inputMode="numeric" disabled={submitting} error={errors.documentNumber} value={values.documentNumber} onChange={(e) => set("documentNumber", e.target.value)} /></div><TextField id="email" label="Correo electrónico" type="email" autoComplete="email" disabled={submitting} error={errors.email} value={values.email} onChange={(e) => set("email", e.target.value)} /><TextField id="phone" label="Teléfono" type="tel" autoComplete="tel" disabled={submitting} error={errors.phone} value={values.phone} onChange={(e) => set("phone", e.target.value)} /><TextField id="password" label="Contraseña" type="password" autoComplete="new-password" disabled={submitting} error={errors.password} value={values.password} onChange={(e) => set("password", e.target.value)} /><button className={styles.authButton} disabled={submitting} type="submit">{submitting ? "Creando cuenta…" : "Crear cuenta"}</button><p className={styles.authHint}>¿Ya tienes cuenta? <Link className={styles.authLink} href="/iniciar-sesion">Inicia sesión</Link>.</p></form>;
}
